name: 'actions-helm-package'
description: 'Helm package & push to nexus repository'
author: 'PeterHallgato'
branding:
  color: 'blue'
  icon: 'package'
inputs:
  helm_repository_url:
    description: "Helm repository url"
    required: true
  helm_repository_name:
    description: "Helm repository name"
    required: true
  helm_repository_user:
    description: "Helm repository user"
    required: true
  helm_repository_password:
    description: "Helm repository password"
    required: true
  helm_repository_insecure:
    description: "Helm repository insecure mode (default false)"
    required: false
  helm_chart_dir:
    description: "Helm chart dir, default is repository root."
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'